App:
  name: 'go-link-shortener'
  version: '0.8.1'

Http:
  port: '8081'

Log:
  level: 'debug'

PG:
  DSN: 'user=root password=root host=0.0.0.0:5432 dbname=shortener pool_max_conns=10'
  URL: "postgres://root:root@localhost:5432/shortener"
