version: "3"
services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortener
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"